version: "3.9"

services:

  db:
    image: postgres:16
    container_name: blog_postgres
    environment:
      POSTGRES_DB: blog_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blog_network

  app:
    build: .
    container_name: blog_api_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: blog_api
      DB_USER: postgres
      DB_PASSWORD: 123456
      JWT_SECRET: my_super_secret_key
      JWT_EXPIRES: 1h
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - blog_network

volumes:
  db_data:

networks:
  blog_network: